# User specified paths and paramters
threads: 48 # Threads
DIR_output: "/home/zeqianli/project/zeqian/Carbon/data/zeqian" # Output directory.
# FILE_sample_list: "/home/zeqianli/Kuehn/Carbon/snakemake/config/strains_test.txt" # If not provided, run the pipeline on all samples 
PATH_KOFAMSCAN_PROFILES: "/home/zeqianli/project/zeqianli/bin/kofamscan/profiles" # Database path for KofamScan
PATH_KOFAMSCAN_KO_LIST: "/home/zeqianli/project/zeqianli/bin/kofamscan/ko_list" # KO list path for KofamScan
FILE_BIGG_METABOLITES: "/home/zeqianli/Kuehn/Carbon/snakemake/config/bigg_models_metabolites.txt" # BIGG metabolite file 
FILE_INITIAL_MEDIUM: "/home/zeqianli/Kuehn/Carbon/snakemake/config/media_cfree.tsv" # Initial c-free medium for FBA simulation
PATH_CPLEX: /home/zeqianli/scratch-midway3/bin/cplex/cplex/python/3.9/x86-64_linux # CPLEX path 

# Paths relative to DIR_output
DIR_assembly: "assembly" # User should copy assembly files to this directory.
DIR_faa: "faa" # faa files
DIR_fna: "fna" # faa files
DIR_16S: "16S"
DIR_KOFAMSCAN: "kofamscan" # KofamScan output
DIR_TEMP: ".tmp" # Temperature output directory for KofamScan
DIR_CARVEME: "carveme" # Carveme output
DIR_FBA_PREDICTION: "fba_prediction" # FBA prediction output